### ISSUE TITLE
handle ERROR_MORE_DATA for pipe

### ISSUE THREAD

**Issue by lynnux** [alexcrichton/miow#11]
According to https://msdn.microsoft.com/en-us/library/windows/desktop/aa365467(v=vs.85).aspx:
```
If a named pipe is being read in message mode and the next message is longer than the nNumberOfBytesToRead parameter specifies, ReadFile returns FALSE and GetLastError returns ERROR_MORE_DATA. The remainder of the message can be read by a subsequent call to the ReadFile or PeekNamedPipefunction.
```
so `ReadFile` in handle.rs should check ERROR_MORE_DATA

**Comment by alexcrichton** [comment]
Thanks for the report! I think right now this'd need some intrusive support to get this working. The library as-is I believe doesn't support creating message-based pipes, so perhaps this'd be added if there were new types to handle message-based pipes?

**Comment by lynnux** [comment]
Oh, that's right, I did not noticed the 'message mode', sorry for the trouble.
