### ISSUE TITLE
Is it possible to wait on other objects, like semaphores?

### ISSUE THREAD

**Issue by Vypo** [alexcrichton/miow#14]
Let me preface this by saying I'm not a Windows developer by a long shot, so this might be a ridiculous question.

That said, is it possible to add a `HANDLE` you get from, say, [`CreateSemaphore`](https://msdn.microsoft.com/en-us/library/windows/desktop/ms682438(v=vs.85).aspx)?

It seems like there's [`WaitForMultipleObjectsEx`](https://msdn.microsoft.com/en-us/library/windows/desktop/ms687028(v=vs.85).aspx), but that doesn't directly map to IOCPs as far as I can tell.

**Comment by alexcrichton** [comment]
AFAIK yeah you can connect them to the `WaitFor*` functions but I don't think there's a way to hook it up to IOCP

**Comment by Vypo** [comment]
Alright, thanks! I'll take a look at some other options. There's always named pipes!
