### ISSUE TITLE
Failing to compile

### ISSUE THREAD

**Issue by dimbleby** [alexcrichton/miow#2]
The immediate problem is this:

```
native library `ws2_32` is being linked to by more than one package, and can only be linked to by one package

  ws2_32-sys v0.2.0
  ws2_32-sys v0.1.0
```
That's easily fixed by having Cargo.toml update its dependency on `ws2_32-sys`.  

But then we get into a tangle of: where are the IP and sockets structures defined?
-  if we don't update the `libc` dependency to `0.2` then we find two versions of `sockaddr_in6` (one from `libc` and one from `winapi`)
-  if we do update the `libc` dependency to `0.2` then we fail to import `libc::sockaddr`

... so more invasive surgery is required.

cf rust-lang-nursery/libc#45

**Comment by alexcrichton** [comment]
Ah looks like I forgot to update this! I've now pushed a version with updated dependencies.
