### ISSUE TITLE
WSARecv without expected error: remote socket shutdown

### ISSUE THREAD

**Issue by viperscape** [alexcrichton/miow#3]
Should this throw a wsarecv error for shutdown of socket? It does not; is this expected?

https://msdn.microsoft.com/en-us/library/windows/desktop/ms741688(v=vs.85).aspx
https://msdn.microsoft.com/en-us/library/windows/desktop/ms740668(v=vs.85).aspx#WSAESHUTDOWN

```rust
fn recv_test() {
    let mut cp = CompletionPort::new(10).unwrap();
    let server = TcpListener::bind("127.0.0.1:6000").unwrap();

    let j = thread::spawn(move || {
        let mut client = TcpStream::connect("127.0.0.1:6000").unwrap();
        thread::sleep_ms(50); // wait for server to add socket to iocp, just in case for this test
        client.shutdown(std::net::Shutdown::Both);
        drop(client);
    });
    
    let mut server = server.incoming().next().unwrap().unwrap(); // client and server threads are unblocked now
    cp.add_socket(99,&server);
    thread::sleep_ms(120); // sleep while the client thread shuts down
    let mut buf = [0;10];
    unsafe { server.read_overlapped(&mut buf,&mut Overlapped::zero()); }
    
    let r = cp.get(None).unwrap();
    println!("{:?}",r);
}
```

prints:

```
CompletionStatus(OVERLAPPED_ENTRY { lpCompletionKey: 99, lpOverlapped: 0x3dffc68, Internal: 0, dwNumberOfBytesTransferred: 0 })
```

**Comment by alexcrichton** [comment]
I think that this is indicated through the return value of `read_overlapped` which returns `Ok(true)` indicating that the operation completed immediately, and then the completion is received later indicating that 0 bytes were transferred (e.g. it was shut down).

The `WSAESHUTDOWN` may not be returned in this case but perhaps when you do something like write to a closed socket?

As a side note as well you'll want to make sure that the `Overlapped::zero` outlives the span between `read_overlapped` and `get`, so you'll probably want to pull it into a temporary in this function.

**Comment by viperscape** [comment]
Ah ok that makes sense, thanks for the insight and tip!
