### ISSUE TITLE
Example reading strings

### ISSUE THREAD

**Issue by mmacedoeu** [alexcrichton/miow#4]
I am a bit new with Rust, getting lost trying to read a String from a pipe. I am trying to implement a Pipe to Redis Broker https://github.com/mmacedoeu/pipetoredis.rs but getting lost with:

```rust
let mut b : String = String::new();
let mut over = Overlapped::zero();
unsafe {
    a.read_overlapped(&mut b.as_ref(), &mut over);
}
```

I would like to handle broken pipes too. How can I do it ?

**Comment by alexcrichton** [comment]
Thanks for the report! This library is currently fairly low-level so it doesn't provide the ability to read directly into strings, but rather just into byte buffers. What you'll want to do is to read the data into a `Vec<T>` likely along the lines of:

```rust
let mut data = Vec::with_capacity(1024);

let result = unsafe {
    data.set_len(1024);
    a.read_overlapped(&mut data, &mut overlapped)
};

// check `result` to see if an error happened

// wait for the I/O to complete
let notification = completion_port.get().unwrap();
data.set_len(notification.bytes_transferred()); // update how many bytes were read

let string = String::from_utf8(data).unwrap() // parse utf-8 to a string

// work with string
```

I believe that broken pipes are handled in the return value from `read_overlapped` as well.
